with-expecter: true
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
packages:
  github.com/envoyproxy/envoy/contrib/golang/common/go/api:
    config:
      dir: test/mock/envoy
      outpkg: mock_envoy
    interfaces:
      FilterCallbackHandler:
      ConfigCallbackHandler:
      RequestHeaderMap:
      ResponseHeaderMap:
      CounterMetric:
      GaugeMetric:

  github.com/ardikabs/gonvoy:
    config:
      dir: test/mock/gonvoy
      outpkg: mock_gonvoy
    interfaces:
      Context:
      Configuration:
      Cache:
      HttpFilter:
      HttpFilterHandler:
      HttpFilterHandlerManager:
      Metrics:
