services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.example
    ports:
      - 8001:8001
      - 10000:10000
    command:
      - "/usr/local/bin/envoy"
      - -c
      - /etc/envoy.yaml
      - --log-level warn
      - --component-log-level http:info,golang:info,misc:error
    volumes:
      - ./example/go-simple-extension/envoy.yaml:/etc/envoy.yaml
    # environment:
    #   - GONVOY_ALLOW_REQUEST_HEADER_PHASE=0
    #   - GONVOY_ALLOW_RESPONSE_HEADER_PHASE=0
    #   - GONVOY_ALLOW_REQUEST_BODY_PHASE=0
    #   - GONVOY_ALLOW_RESPONSE_BODY_PHASE=0
  helloworld_service:
    # image: registry.k8s.io/echoserver:1.10
    # if you are using Apple M1, use below image, otherwise above.
    image: kicbase/echo-server:1.0
  podinfo_service:
    image: ghcr.io/stefanprodan/podinfo:6.5.0
