services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.example
    ports:
      - 8001:8001
      - 10000:10000
    command:
      - "/usr/local/bin/envoy"
      - -c
      - /etc/envoy.yaml
      - --log-level warn
      - --component-log-level http:info,golang:info,misc:error
    volumes:
      - ./example/go-simple-extension/envoy.yaml:/etc/envoy.yaml
  helloworld_service:
    # image: registry.k8s.io/echoserver:1.10
    # if you are using Apple M1, use below image, otherwise above.
    image: kicbase/echo-server:1.0
  podinfo_service:
    image: ghcr.io/stefanprodan/podinfo:6.6.2
  grpc_podinfo_service:
    image: ghcr.io/stefanprodan/podinfo:6.6.2
    command:
      - ./podinfo
      - --port=9898
      - --grpc-port=9999
      - --grpc-service-name=podinfo
      - --level=info
