name: Test

on:
  push:
    branches:
      - main
      - "release/v*"
    paths-ignore:
      - "**/*.md"

  pull_request:
    branches:
      - main
      - "release/v*"
    paths-ignore:
      - "**/*.md"

  workflow_call:

jobs:
  audit:
    name: Auditing the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1

      - name: Install make
        run: |
          sudo apt update -y
          sudo apt install make curl git -y

      - name: Run audit
        run: |
          make lint
          make test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./output/coverage.out
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

  e2e-test:
    name: E2E Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v2

      - name: Install Docker Compose Plugin
        run: |
          ./hack/install-docker-compose.sh

      - name: Run E2E
        run: |
          make e2e
